cabal-version:      3.0
name:               aoc

-- The package version.
-- See the Haskell package versioning policy (PVP) for standards
-- guiding when and how versions should be incremented.
-- https://pvp.haskell.org
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Sam Noedel
maintainer:         sam.noedel@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common shared
    ghc-options:      -Wall
    default-language: Haskell2010
    build-depends:    base ^>=4.17.2.1

library
    import:           shared
    hs-source-dirs:   lib
    build-depends:    containers ^>=0.7
    exposed-modules:  Day01

executable runner
    import:           shared
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    aoc

test-suite test
    import:           shared
    build-depends:    HUnit ^>=1.6.2.0, containers ^>=0.7
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    build-depends:    aoc
