[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
num-traits = "0.2.17"
regex = "1.10.2"
aoc_macros = { path = "../aoc_macros" }
aoc_runner = { path = "../aoc_runner" }
