[package]
name = "aoc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
aoc_runner = { path = "../aoc_runner" }
proc-macro2 = "^1.0.70"
quote = "^1.0.33"
syn = { version = "^2.0.39", features = ["full"] }
